In [1]:
import os
import h5py
import pandas as pd
from tqdm import tqdm
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from helper_functions import *

In [3]:
original_df = pd.read_csv('processed_data/expanded_df_formatted.csv')
original_df = original_df.drop(columns=['secondary_labels', 'matches_primary', 'matches_secondary', 'top_class'])

spec_averages = np.load('processed_data/spectrogram_averages.npy')
h5_path = 'processed_data/expanded_spectrograms.h5'

In [4]:
original_df['spec_averages'] = spec_averages
original_df

,working_df_idx,samplename,chunk_id,filepath,primary_label,spec_averages
0,0,1139490-CSA36385-0,0,/kaggle/input/birdclef-2025/train_audio/113949...,1139490,0.053886
1,0,1139490-CSA36385-1,1,/kaggle/input/birdclef-2025/train_audio/113949...,1139490,0.355889
2,0,1139490-CSA36385-2,2,/kaggle/input/birdclef-2025/train_audio/113949...,1139490,0.336834
3,0,1139490-CSA36385-3,3,/kaggle/input/birdclef-2025/train_audio/113949...,1139490,0.375459
4,0,1139490-CSA36385-4,4,/kaggle/input/birdclef-2025/train_audio/113949...,1139490,0.375009
...,...,...,...,...,...,...
115352,28562,ywcpar-iNat819873-0,0,/kaggle/input/birdclef-2025/train_audio/ywcpar...,ywcpar,0.437080
115353,28562,ywcpar-iNat819873-1,1,/kaggle/input/birdclef-2025/train_audio/ywcpar...,ywcpar,0.429156
115354,28562,ywcpar-iNat819873-2,2,/kaggle/input/birdclef-2025/train_audio/ywcpar...,ywcpar,0.407852
115355,28563,ywcpar-iNat922688-0,0,/kaggle/input/birdclef-2025/train_audio/ywcpar...,ywcpar,0.357751
115356,28563,ywcpar-iNat922688-1,1,/kaggle/input/birdclef-2025/train_audio/ywcpar...,ywcpar,0.338672

In [ ]:
first_n = 5
num_classes = original_df['primary_label'].nunique()

top_n_samples = original_df.sort_values('spec_averages', ascending=False).groupby('primary_label').head(first_n)
assert len(top_n_samples) <= first_n * num_classes

top_n_samples

,working_df_idx,samplename,chunk_id,filepath,primary_label,spec_averages
88730,22380,thlsch3-XC114701-5,5,/kaggle/input/birdclef-2025/train_audio/thlsch...,thlsch3,0.701538
88726,22380,thlsch3-XC114701-1,1,/kaggle/input/birdclef-2025/train_audio/thlsch...,thlsch3,0.686845
46726,11667,grnkin-XC957618-3,3,/kaggle/input/birdclef-2025/train_audio/grnkin...,grnkin,0.686672
87229,22055,strowl1-XC351411-1,1,/kaggle/input/birdclef-2025/train_audio/strowl...,strowl1,0.676858
57682,14164,paltan1-XC525435-1,1,/kaggle/input/birdclef-2025/train_audio/paltan...,paltan1,0.671782
...,...,...,...,...,...,...
3886,738,65419-iNat48209-0,0,/kaggle/input/birdclef-2025/train_audio/65419/...,65419,0.293113
4168,851,66531-iNat40682-1,1,/kaggle/input/birdclef-2025/train_audio/66531/...,66531,0.220647
4167,851,66531-iNat40682-0,0,/kaggle/input/birdclef-2025/train_audio/66531/...,66531,0.214696
3884,737,65419-iNat48180-1,1,/kaggle/input/birdclef-2025/train_audio/65419/...,65419,0.177381
3883,737,65419-iNat48180-0,0,/kaggle/input/birdclef-2025/train_audio/65419/...,65419,0.171268

In [ ]:
save_filtered_data(original_df=original_df,
                   filtered_df=top_n_samples,
                   name=f'top_{first_n}_samples',
                   save_npy=True)

Using small filter

Building spectrogram dict:  40%|█████████████████████████████████████████████▎                                                                   | 409/1020 [05:50<08:16,  1.23it/s]

In [7]:
best_n = 1 # matches the number of training samples in the baseline
best_samples_per_file = original_df.sort_values('spec_averages').groupby('filepath').head(best_n)
best_samples_per_file

,working_df_idx,samplename,chunk_id,filepath,primary_label,spec_averages
110982,27744,yeofly1-XC328921-1,1,/kaggle/input/birdclef-2025/train_audio/yeofly...,yeofly1,0.002946
91363,23025,trokin-iNat162152-0,0,/kaggle/input/birdclef-2025/train_audio/trokin...,trokin,0.005326
80651,20463,speowl1-XC233090-2,2,/kaggle/input/birdclef-2025/train_audio/speowl...,speowl1,0.006295
84014,21163,strcuc1-XC358593-0,0,/kaggle/input/birdclef-2025/train_audio/strcuc...,strcuc1,0.011209
106426,26587,yebfly1-XC377357-0,0,/kaggle/input/birdclef-2025/train_audio/yebfly...,yebfly1,0.011579
...,...,...,...,...,...,...
38690,9431,fotfly-XC115604-0,0,/kaggle/input/birdclef-2025/train_audio/fotfly...,fotfly,0.647084
15212,3735,blbgra1-XC800269-0,0,/kaggle/input/birdclef-2025/train_audio/blbgra...,blbgra1,0.647175
543,81,21211-XC913839-0,0,/kaggle/input/birdclef-2025/train_audio/21211/...,21211,0.652588
46721,11665,grnkin-XC939554-0,0,/kaggle/input/birdclef-2025/train_audio/grnkin...,grnkin,0.659847
82499,20810,srwswa1-XC788994-0,0,/kaggle/input/birdclef-2025/train_audio/srwswa...,srwswa1,0.668190

In [ ]:
save_filtered_data(original_df=original_df,
                   filtered_df=best_samples_per_file,
                   name='best_samples_per_file',
                   save_npy=True)

Using large filter

Building spectrogram dict:  15%|████████████████▍                                                                                            | 4317/28564 [56:17<5:16:12,  1.28it/s]